AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  EmailAddress:
    Type: String
    Description: (Required) Your email address.

Resources:
  SendAlertFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          SNS_TOPIC: !Ref SNSAlertTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SNSAlertTopic.TopicName

  SNSAlertTopic:
    Type: 'AWS::SNS::Topic'
  
  MySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EmailAddress
      Protocol: email
      TopicArn: !Ref 'SNSAlertTopic'

  SoracomAlertManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource: !GetAtt SendAlertFunction.Arn